MOV-AI/movai-core-shared

.bumpversion.cfg, build-requirements.txt, movai_core_shared/core/securepassword.py, requirements.txt, setup.py
this branch contains the necessary changes for the updated split
jira:
https://movai.atlassian.net/browse/BP-829?atlOrigin=eyJpIjoiYjJhMWY1NGJhNDdlNDU4NWJkYTA3MzQ2ODBkNDExMDgiLCJwIjoiaiJ9
'- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue'
[^note]:
Put an `x` into the [ ] to show you have filled the information.
The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
You can override it by creating .github/pull_request_template.md  in your own repository
=> Feature bp 829 prepare for deployment on movai core shared

.github/workflows/DeployOnGitRelease.yml, .github/workflows/DeployOnMergeMain.yml
cicd: password for autoraise commit
=> cicd: password for autoraise commit

movai_core_shared/common/utils.py, movai_core_shared/consts.py, movai_core_shared/envvars.py, movai_core_shared/logger.py
[BP-923](https://movai.atlassian.net/browse/BP-923) - connect telegraph logs viewer to logs db
[BP-923]: https://movai.atlassian.net/browse/BP-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-923 Connect telegraph logs viewer to logs db

movai_core_shared/logger.py
[BP-957](https://movai.atlassian.net/browse/BP-957) - removing tags from log message
[BP-957]: https://movai.atlassian.net/browse/BP-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "BP-957 - removing tags from log message (#50)"

movai_core_shared/core/message_client.py
[BP-970](https://movai.atlassian.net/browse/BP-970) - return feedback from metrics api
[BP-970]: https://movai.atlassian.net/browse/BP-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-970 - return feedback from metrics api

movai_core_shared/__init__.py, movai_core_shared/recovery.py
moved recovery const and enum that will be accessible from the spawner
see https://github.com/MOV-AI/data-access-layer/pull/134
=> added recovery enum and const

movai_core_shared/__init__.py, movai_core_shared/common/utils.py, movai_core_shared/core/message_client.py, movai_core_shared/core/zmq_client.py, movai_core_shared/recovery.py
[BP-970](https://movai.atlassian.net/browse/BP-970) - return feedback from metrics api
[BP-971](https://movai.atlassian.net/browse/BP-971) - general fixes
[BP-975](https://movai.atlassian.net/browse/BP-975) - added recovery to shared
[BP-970]: https://movai.atlassian.net/browse/BP-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-971]: https://movai.atlassian.net/browse/BP-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-975]: https://movai.atlassian.net/browse/BP-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> version 2.4.1.10

movai_core_shared/consts.py, movai_core_shared/logger.py
[BP-1023](https://movai.atlassian.net/browse/BP-1023) - display message server messages in readable format
[BP-1023]: https://movai.atlassian.net/browse/BP-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1023 - display message server messages in readable format

.github/CODEOWNERS, movai_core_shared/logger.py
[BP-990](https://movai.atlassian.net/browse/BP-990) - errors on zmq_client
[BP-990]: https://movai.atlassian.net/browse/BP-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-990 - errors on zmq_client

movai_core_shared/core/base_command.py
[BP-1022](https://movai.atlassian.net/browse/BP-1022) - add metric tool to initiate metric operations from terminal
[BP-1022]: https://movai.atlassian.net/browse/BP-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1022 - add metric tool to initiate metric operations from terminal

movai_core_shared/envvars.py, movai_core_shared/logger.py
[BP-1025](https://movai.atlassian.net/browse/BP-1025) - logs from spawner are not displayed
[BP-1025]: https://movai.atlassian.net/browse/BP-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1025 - logs from spawner are not displayed

movai_core_shared/core/zmq_client.py
* added mutexes to the zmq port, when working with multithreaded
=> added mutexes to the zmq port, when working with multithreaded (#73)

movai_core_shared/logger.py
=> another fix (#83)

movai_core_shared/envvars.py, movai_core_shared/logger.py
add the ability to specify a log name and location
Added another Env Var name “MOVAI_LOG_FILE”
that you can specify the name and absolute location
and changed the default 
to “/opt/mov.ai/app/movai.log” 
if you don’t want to change it
=> added functinality to change log file name

movai_core_shared/core/message_client.py, movai_core_shared/envvars.py, movai_core_shared/logger.py
add the ability to specify a log name and location
see bp-1051
Added another Env Var name “MOVAI_LOG_FILE”
that you can specify the name and absolute location
and changed the default
to “/opt/mov.ai/app/movai.log”
if you don’t want to change it
=> new release

movai_core_shared/core/message_client.py, movai_core_shared/core/zmq_client.py, movai_core_shared/core/zmq_server.py, movai_core_shared/envvars.py, movai_core_shared/logger.py, movai_core_shared/messages/general_data.py, movai_core_shared/messages/stress_data.py
[BP-1045](https://movai.atlassian.net/browse/BP-1045) - migrate message server dispatchers to zmqserver
[BP-1046](https://movai.atlassian.net/browse/BP-1046) - ZMQ error after running the flow for a while
[BP-1049](https://movai.atlassian.net/browse/BP-1049) - Metrics are intermittendly breaking
[BP-1057](https://movai.atlassian.net/browse/BP-1057) - Logs API response structure was changed
[BP-1045]: https://movai.atlassian.net/browse/BP-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1046]: https://movai.atlassian.net/browse/BP-1046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1049]: https://movai.atlassian.net/browse/BP-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> version 2.4.1.21

movai_core_shared/core/message_client.py, movai_core_shared/core/zmq_client.py
[BP-1079](https://movai.atlassian.net/browse/BP-1079) - backend does not start
[BP-1079]: https://movai.atlassian.net/browse/BP-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1079 - backend does not start

movai_core_shared/core/message_client.py, movai_core_shared/core/zmq_client.py
- [BP-1079](https://movai.atlassian.net/browse/BP-1079) - backend does not start
[BP-1079]: https://movai.atlassian.net/browse/BP-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/bp 1079/backend does not start

.github/workflows/DeployOnMergeMain.yml, README.md
removing setup.py ignore from github workflow merge on main
=> Version 2.4.1.30

movai_core_shared/common/utils.py
[BP-1088](https://movai.atlassian.net/browse/BP-1088) - Permission denied in message-server
[BP-1088]: https://movai.atlassian.net/browse/BP-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1088 - Permission denied in message-server

movai_core_shared/core/zmq/zmq_client.py, movai_core_shared/core/zmq/zmq_publisher.py, movai_core_shared/core/zmq/zmq_server.py, movai_core_shared/core/zmq/zmq_subscriber.py, movai_core_shared/messages/alert_data.py
[BP-1127](https://movai.atlassian.net/browse/BP-1127) - Flows do not start when triggered
[BP-1127]: https://movai.atlassian.net/browse/BP-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1127 - Flows do not start when triggered

movai_core_shared/core/zmq/zmq_client.py, movai_core_shared/core/zmq/zmq_publisher.py, movai_core_shared/core/zmq/zmq_server.py, movai_core_shared/core/zmq/zmq_subscriber.py, movai_core_shared/messages/alert_data.py
[BP-1127](https://movai.atlassian.net/browse/BP-1127) - Flows do not start when triggered
[BP-1127]: https://movai.atlassian.net/browse/BP-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Version 2.5.0.4

movai_core_shared/common/utils.py, movai_core_shared/logger.py
[BP-872](https://movai.atlassian.net/browse/BP-872) - convert frontend callback to rest api 
* fix is_enterprise function
[BP-872]: https://movai.atlassian.net/browse/BP-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Version 2.5.0.6

movai_core_shared/exceptions.py
[BP-872](https://movai.atlassian.net/browse/BP-872) - convert frontend callback to rest api
fix missing exception
[BP-872]: https://movai.atlassian.net/browse/BP-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Version 2.5.0.7

movai_core_shared/core/base_command.py, movai_core_shared/messages/alert_data.py, movai_core_shared/messages/email_data.py, movai_core_shared/messages/general_data.py, movai_core_shared/messages/metric_data.py, movai_core_shared/messages/stress_data.py, setup.py
pydantic baseline for 2.4.1:
[BP-1001](https://movai.atlassian.net/browse/BP-1001) - create Callback pydantic class
[BP-1002](https://movai.atlassian.net/browse/BP-1002) - create Configuration pydantic class
[BP-999](https://movai.atlassian.net/browse/BP-999) - create Flow pydantic class
[BP-1110](https://movai.atlassian.net/browse/BP-1110) - create Message pydantic class
[BP-1000](https://movai.atlassian.net/browse/BP-1000) - create Node pydantic class
[BP-1009](https://movai.atlassian.net/browse/BP-1009) - create Ports pydantic class
[BP-1114](https://movai.atlassian.net/browse/BP-1114) - create System pydantic class
[BP-1001]: https://movai.atlassian.net/browse/BP-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BP-1002]: …
=> Version 2.5.0.10

movai_core_shared/exceptions.py
[BP-1161](https://movai.atlassian.net/browse/BP-1161) - fix new and init on MovaiBaseModel
[BP-1161]: https://movai.atlassian.net/browse/BP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1161 - fix new and init on MovaiBaseModel

movai_core_shared/exceptions.py
[BP-1161](https://movai.atlassian.net/browse/BP-1161) - fix new and init on MovaiBaseModel
[BP-1161]: https://movai.atlassian.net/browse/BP-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Version 2.5.0.11

.pre-commit-config.yaml, .pylintrc, movai_core_shared/core/zmq/zmq_server.py, movai_core_shared/envvars.py
Releasing SPAWNER_BIND_ADDR switch to unix socket (#144)
=> Releasing SPAWNER_BIND_ADDR switch to unix socket (#144)

setup.py
Add 2 variables to identify transport types.
=> RP-2100 Deploy changes to enable context issue solving

movai_core_shared/consts.py
=> Release : Update timeout values for killing nodes (#167)

.bumpversion.cfg, CHANGELOG.md, setup.py
- [BP-1313](https://movai.atlassian.net/browse/BP-1313): Move development to main branch
[BP-1313]: https://movai.atlassian.net/browse/BP-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump version to v3.0.0

CHANGELOG.md, movai_core_shared/messages/command_data.py, pyproject.toml
- [BP-1388](https://movai.atlassian.net/browse/BP-1388): Exception when starting node via tree view on a member
[BP-1388]: https://movai.atlassian.net/browse/BP-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make flow field optional in command data

movai_core_shared/log_handlers/callback_handler.py, movai_core_shared/log_handlers/callback_logger.py, movai_core_shared/log_handlers/generic_handler.py, movai_core_shared/logger.py, tests/test_logging.py
=> BP-1370 refactor callback loghandler

CHANGELOG.md, pyproject.toml
=> Bump version of #198

CHANGELOG.md, pyproject.toml
Reverts MOV-AI/movai-core-shared#200
=> Revert "DP-1798: Fix Docker exception when using quickstart"

CHANGELOG.md, movai_core_shared/logger.py, movai_core_shared/messages/metric_data.py, pyproject.toml
- [BP-1354](https://movai.atlassian.net/browse/BP-1354): Add db_name to MetricQueryData
[BP-1354]: https://movai.atlassian.net/browse/BP-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1354: Add db_name to MetricQueryData

movai_core_shared/messages/metric_data.py
* Add missing log query fields
=> Add missing log query fields

.pre-commit-config.yaml, .pylintrc, CHANGELOG.md, movai_core_shared/common/utils.py, movai_core_shared/core/base_command.py, movai_core_shared/core/message_client.py, movai_core_shared/core/securepassword.py, movai_core_shared/core/zmq/zmq_client.py, movai_core_shared/core/zmq/zmq_helpers.py, movai_core_shared/core/zmq/zmq_server.py, movai_core_shared/log_handlers/callback_handler.py, movai_core_shared/log_handlers/generic_handler.py, movai_core_shared/logger.py, movai_core_shared/messages/log_data.py, movai_core_shared/messages/metric_data.py, movai_core_shared/messages/sms_data.py, movai_core_shared/messages/stress_data.py, movai_core_shared/recovery.py, pyproject.toml, tests/common/zmq_server.py, tests/test_logging.py, tox.ini
- [BP-1462](https://movai.atlassian.net/browse/BP-1462): Translation implementation
- Support log placeholders
[BP-1462]: https://movai.atlassian.net/browse/BP-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BP-1462: Translation implementation

movai_core_shared/messages/log_data.py, movai_core_shared/messages/metric_data.py
- Add tags to logs query and response
=> Add tags to logs query and response
